### ISSUE TITLE
machine resource's 'bootstrap_options --> user_data' no longer has a default value (Windows, Ec2)

### ISSUE THREAD

**Issue by jedugas** [chef/chef-provisioning-aws#384] opened 2015-10-29 23:30 UTC
Though a default user_data script is defined in the driver code (as a <powershell> script), it's never actually used. When trying to converge a new machine, it errors (repeatably) due to WinRM being disabled.

OK I've verified this by (1) logging into the non-converging Ec2 Win instance to confirm the WinRM configuration differs significantly from that in the code, and (2) by copying the user_data <powershell> script from the actual driver code and pasting in into bootstrap_options --> user_data for a new Ec2 Win instance, resulting in a successful convergence.

Previous, working versions (i.e. 1.3.1) of this driver used to apply the default user_data based on the is_windows flag, but this logic no longer exists. One suggestion is to add back that is_windows logic, but to also append a non-nil user_data value to the default one (for extensibility).

**Comment by pplante** [comment] 2015-11-09 20:34
I think this is the cause of my bug here: https://github.com/chef/chef-provisioning-aws/issues/388

**Comment by pplante** [comment] 2015-11-09 20:37
Looking through the commit log, I think there was an error made here: https://github.com/chef/chef-provisioning-aws/commit/ba0ee0e53780bc78c5cef0c08564946eb339e405

**Comment by hh** [comment] 2015-11-17 15:53
Sorry about that, we should keep that logic.

**Comment by hh** [comment] 2015-11-30 19:17
@jedugas working with @tyler-ball to get this rolled back in

**Comment by tyler-ball** [comment] 2015-12-01 17:21
Fixed by https://github.com/chef/chef-provisioning-aws/pull/400

**Closed by tyler-ball** 2015-12-01 17:21 UTC
Labels: Bug, Reviewing
