### ISSUE TITLE
AWS::EC2::Errors::InvalidInstanceID::NotFound When creating a `machine` 

### ISSUE THREAD

**Issue by afiune** [chef/chef-provisioning-aws#264] opened 2015-07-28 01:49 UTC
This is a very aleatory issue, when creating a new instance on `AWS` using the `machine` resource sometimes it fails with the error:

```
Problem: AWS::EC2::Errors::InvalidInstanceID::NotFound

The instance ID 'i-afb562a2' does not exist
```

When it indeed created the instance.

**Comment by tyler-ball** [comment] 2015-07-28 15:15
This keeps rearing its head - I think I may have fixed it in https://github.com/chef/chef-provisioning-aws/pull/263

The issue is that immediately after creating an instance we check and [retry](https://github.com/chef/chef-provisioning-aws/blob/530670dc418827a22ea77a846faa603a9c62e199/lib/chef/provisioning/aws_driver/aws_provider.rb#L274-L289) until it is ready for tagging.  Previsouly I was only retrying if the status was bad, but if you call `aws_object.status` before it is actually created you see the error above.

@afiune Can you try with the branch from that PR I linked and see if you see any issues?

**Comment by afiune** [comment] 2015-07-30 13:47
@tyler-ball yup, I will give it a try today! :smile:

**Comment by tyler-ball** [comment] 2015-08-18 20:41
Hey @afiune - I'm going to close this.  Will you re-open if you see these start popping up again?

**Closed by tyler-ball** 2015-08-18 20:41 UTC
Labels: Bug, Feedback Requested, Triaged
