### ISSUE TITLE
AWS::EC2::Errors::RequestLimitExceeded: Request limit exceeded - when launching many instances in a batch

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-provisioning-aws#214] opened 2015-05-27 23:31 UTC
stack trace:
```
Generated at 2015-05-27 16:14:54 -0700
AWS::EC2::Errors::RequestLimitExceeded: machine_batch[fly_my_pretties_fly-loadtester-uswest-2a] (ec-harness::loadtesters line 86) had an error: AWS::EC2::Errors::RequestLimitExceeded: Request limit exceeded.
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:375:in `return_or_raise'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `run_instances'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.64.0/lib/aws/ec2/instance_collection.rb:304:in `create'
/Users/irving/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.2.1/lib/chef/provisioning/aws_driver/driver.rb:1005:in `block in create_many_instances'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:93:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
```

**Comment by Jimflip** [comment] 2015-07-03 20:33
We are seeing this issue too, ideally we want to add a sleep between each instance in batch in order to slow things down.

**Comment by tyler-ball** [comment] 2015-07-07 21:24
When we use machine_batch we use the `Parallelizer` which just spins up a thread for each AWS `run_instance` request.  We either need to expose a way to specify the number of threads in the pool, or document this if it already exists.  We also need to default it to a number which AWS won't get mad at.

Finally, another way we could fix this would be to make a batch request for instances (if that is possible).

**Comment by gmiranda23** [comment] 2015-07-07 21:34
Semi off-topic, but a workaround until this is fixed can be had by way of auto-scaling groups.  For example, rather than issuing 100 API requests to create 100 ec2 instances, you can instead create an aws_auto_scaling_group that doesn't actually scale.

    aws_auto_scaling_group "my_100_instances" do
        min_size 100
        max_size 100
    end

That's an abuse of autoscaling groups, and only addresses ec2 instances.  But if you found this issue, that might help you until we get a proper fix in place.

**Comment by Jimflip** [comment] 2015-07-14 14:30
So the more we use Chef-provisioning-aws the more we see this issue, i.e. more jobs run in parallel in CI.

The aws-libs from Amazon handle this error and implements retries using a backing off strategy, this is needed here in order to use chef-provisioning at any significant level.

**Comment by tyler-ball** [comment] 2015-07-16 16:51
@Jimflip What is `aws-libs`?  Do you mean the SDKs?  We should investigate to see if this is fixed in the SDK V2

**Comment by Jimflip** [comment] 2015-08-03 16:57
@tyler-ball sorry, yes I mean the SDKs
We have added more services to our cluster and are now seeing this issue consistently.

**Comment by ajeba99** [comment] 2015-08-20 19:32
@tyler-ball @Jimflip @irvingpop 
I am seeing this exact issue.  I also believe #158 is related to this issue but this issue being the root cause.  We found this during a test of spinning up 20 servers (mixed win/lin environment)

My suggested work around is to take out the machine batch and spin one server at a time - still quicker than doing it by hand.  As well as better than refactoring your code to use cloud formation or auto scaling as you're just commenting out two lines.

**Comment by tyler-ball** [comment] 2015-08-21 16:15
@Jimflip Do you know of the ruby SDK supports retries with backoff?  If it did, that would be awesome.  I haven't seen anywhere that says it does...

**Comment by ajeba99** [comment] 2015-08-21 23:00
@tyler-ball 
I opened a ticket with amazon and they said we're getting rate limited because of the number of 'describe_instances' we're doing.  Which, in turn, leads to other failures once the rate limit hits.

I tried using the normal FOG:AWS driver and I didn't get this issue.  From what I could google, it appears the fog driver is able to either batch these in groups of 5 or more efficient use of API requests.

This issue is crippling for us using chef-provisioning-aws at scale using machine_batch.  Just normal on-at-a-time machine sequential builds work fine.  But I would rather not wait 3 hours for 20 windows servers to build - even though it's still faster than most else.

**Comment by tyler-ball** [comment] 2015-08-24 23:20
@ajeba99 I have a PR open where I updated the `machine` resource to use the SDK V2.  Would you mind trying https://github.com/chef/chef-provisioning-aws/pull/293 and seeing if your rate limited errors go away?

I agree that we've been bad about the number of API requests we make.  We should (at least) be caching more information that we get back from AWS - especially for `describe_instances` calls.  We could also limit the number of threads that `machine_batch` spins up (and make this user configurable).

But I'm hoping automatic retry logic with backoffs will work on the short term!

**Comment by ajeba99** [comment] 2015-08-25 20:52
@tyler-ball 
Tried spinning up 20 servers using machine_batch ...
Everything seems to go fine (describes text flies by) until it gets to the run_instances and I get a 
````
Aws::EC2::Errors::InvalidParameterValue Invalid BASE64 encoding of user data
````
then it gets to the 19th and I see 19 and 20 do ...
````
:RequestLimitExceeded Request limit exceeded.
````
Final error is 
````
[2015-08-25T15:46:18-05:00] FATAL: Aws::EC2::Errors::InvalidParameterValue: machine_batch[CreateServers] (@recipe_files:
:C:/chef/CreateServers.rb line 10) had an error: Aws::EC2::Errors::InvalidParameterValue: Invalid BASE64 encoding of use
r data
````

The servers do not get created in AWS.

**Comment by ajeba99** [comment] 2015-08-26 13:46
@tyler-ball I like your idea of a configurable thread limit.  I know I can spin 10 new aws instances using machine_batch just fine.  But it's not just that, becauseif I already have 15 aws instances and adding a 16th would still cause the issue -- a thread governor would resolve that.

I also like the idea, presented above, on a configurable api delay.  Being able to insert a 1 second sleep between each api call would work just fine as well.

I added your changes from 13 hours ago and see no change in my BASE64 encoding issue of user data.  Let me know when you want me to test again.

**Comment by tyler-ball** [comment] 2015-08-26 14:06
Using the SDK V2 branch that was just checked into master:

```
Generated at 2015-08-26 08:01:29 -0600
Aws::EC2::Errors::RequestLimitExceeded: machine_batch[default] (@recipe_files::/Users/tball/chef_repo/cookbooks/test-provisioning/recipes/test.rb line 5) had an error: Aws::EC2::Errors::RequestLimitExceeded: Request limit exceeded.
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-core-2.1.16/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-core-2.1.16/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-core-2.1.16/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-core-2.1.16/lib/seahorse/client/request.rb:70:in `send_request'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-core-2.1.16/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-resources-2.1.16/lib/aws-sdk-resources/request.rb:24:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-resources-2.1.16/lib/aws-sdk-resources/operations.rb:41:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-resources-2.1.16/lib/aws-sdk-resources/operations.rb:87:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-resources-2.1.16/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/driver.rb:1136:in `create_instance_and_reference'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/driver.rb:1084:in `block (2 levels) in create_servers'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.4.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.4.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.4.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.4.1/lib/chef/chef_fs/parallelizer.rb:93:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.4.1/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'%
```

**Comment by tyler-ball** [comment] 2015-08-26 16:04
Please see my PR at https://github.com/chef/chef-provisioning-aws/pull/301 where I add a configurable value for the AWS SDK `retry_limit`.  Also see the notes I made to the CHANGELOG - you can limit the number of threads that `machine_batch` uses with the attribute `max_simultaneous`.

**Comment by ajeba99** [comment] 2015-08-26 20:24
So ...
I added the ````max_simultaneous 5```` option to my machine_batch and saw drastic differences.  This is the only change I made.  I created 20 servers in 37 minutes.

I then changed it to ````max_simultaneous 3```` and created 50 in 136 minutes.

This is the only change I made and it solved my problem of EC2 api limit errors.

**Comment by tyler-ball** [comment] 2015-08-26 20:35
Yeah, it makes me really sad that there was an obvious quick-fix and I didn't know about it until I had invested 1/2 a day looking at it :cry:

But it is documented now, yay!

**Comment by Jimflip** [comment] 2015-08-27 14:20
Alternatively https://github.com/Jimflip/chef-provisioning-aws
has a simple retry which also patched the problem without reducing the number of threads and has been running without problem for a couple of weeks for us.

**Closed** 2015-08-27 17:04 UTC
Labels: Bug, Developing, Documentation

**Comment by rickrdvaughn** [comment] 2016-08-04 21:25
I'm not sure this issue is actually resolved.  Or it has since broken again.  When I use machine_batch with max_simultaneous all the instances get created at once, then only the chef converge runs are bounded by the max_simultaneous value.
