### ISSUE TITLE
AWS EC2 long ids support

### ISSUE THREAD

**Issue by vgirnet** [chef/chef-provisioning-aws#431] opened 2016-01-14 13:52 UTC
AWS EC2 is migrating to long ids this year - from 8 chars to 17 chars - https://aws.amazon.com/ec2/faqs/#longer-ids
https://aws.amazon.com/blogs/aws/heads-up-longer-ec2-ebs-resource-ids-coming-in-2016/

If enabling long id support in EC2 for instances, chef-apply fails with 
```
    NoMethodError
    -------------
    undefined method `id' for nil:NilClass

Full stack trace:
NoMethodError: machine[test-machine] ((chef-apply cookbook)::(chef-apply recipe) line 89) had an error: NoMethodError: undefined method `id' for nil:NilClass
~/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.7.0/lib/chef/provisioning/aws_driver/driver.rb:1273:in `converge_ec2_tags'
~/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.7.0/lib/chef/provisioning/aws_driver/driver.rb:631:in `ready_machine'
~/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.5.1/lib/chef/provider/machine.rb:39:in `block in <class:Machine>'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_ready'
~/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-1.5.1/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:362:in `action_converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:585:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/apply.rb:189:in `run_chef_recipe'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/apply.rb:198:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/apply.rb:211:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-apply:25:in `<top (required)>'
/opt/chefdk/bin/chef-apply:54:in `load'
/opt/chefdk/bin/chef-apply:54:in `<main>'
```

**Comment by elyscape** [comment] 2016-02-10 20:01
This looks like it only needs changing [in the `aws_instance` resource](https://github.com/chef/chef-provisioning-aws/blob/v1.8.0/lib/chef/resource/aws_instance.rb#L16). Changing that line to this should fix this:
```ruby
name =~ /^i-(?:[a-f0-9]{8}|[a-f0-9]{17})$/ ? name : nil
```

**Comment by chrodriguez** [comment] 2016-04-04 15:41
Can this fix be merged? It works, updateing this regexp.... 

Thanks in advance

**Comment by keen99** [comment] 2016-04-07 15:37
Bump.   Just merged PR #474 into my long-lived multi-patch branch that I'm using to support production to "resolve" this -

@jkeiser @tyler-ball this is pretty critical since new accounts (ie, the one I created last night) now default to long IDs.

without this patch, multiple runs will create duplicate instances (since metal thinks the instance doesnt exist) - and destroying a node will not destroy it for the same reason.   This will be massively problematic to new users to this toolkit.....

I just confirmed correct functionality on my brand new account - instances are created once, and then destroyed.   And since the old ID format is still in the regex, this should be 100% safe for short IDs as well.

**Comment by djapg** [comment] 2016-04-07 18:55
Please merge, this is hurting us in new AWS accounts with the long id

**Comment by keen99** [comment] 2016-04-11 15:02
#474 is merged, so this can probably close now. :)

**Comment by elyscape** [comment] 2016-04-11 18:09
There hasn't been a release since, though.

**Comment by keen99** [comment] 2016-04-11 18:22
fair enough.  I've never used a released version, haha. :)

**Comment by tyler-ball** [comment] 2016-04-11 21:32
We typically close issues as we resolve them, so I'm going to do that here and I added a release task to my TODO list

**Comment by elyscape** [comment] 2016-04-11 21:33
Thanks!

**Closed by tyler-ball** 2016-04-11 21:32 UTC
Labels: Bug, Triaged
