### ISSUE TITLE
Updating chef-provisioning-aws breaks chef-client -z functionality with ChefDK 0.4.0 (current version).

### ISSUE THREAD

**Issue by JoeReid-Korrelate** [chef/chef-provisioning-aws#182] opened 2015-04-12 00:03 UTC
Hey guys,

I think there's an issue with the gem dependencies for chef-provisioning-aws that ran afoul of [this issue](http://lists.opscode.com/sympa/arc/chef/2015-04/msg00076.html) with Cheffish while using the current Chef DK.

```[2015-04-11T18:35:18-04:00] ERROR: Unable to activate cheffish-1.1.2, because chef-zero-3.2.1 conflicts with chef-zero (~> 4.0)
[2015-04-11T18:35:18-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)```

**To replicate on Mac OSX:**
* brew cask install chefdk - Installs the current chefdk package - chefdk-0.4.0-1.pkg
* chef verify
* Test a recipe using `chef-client -z simple.rb` or the like, as posted in the ReadME.md
* chef gem update chef-provisioning-aws
* Test a recipe using chef-client -z again.

**ChefDK 4.0 stock gems:**
```
$ chef gem list | grep chef
chef (12.0.3)
chef-dk (0.4.0)
chef-provisioning (0.18)
chef-provisioning-aws (0.2.1)
chef-provisioning-azure (0.1)
chef-provisioning-fog (0.12)
chef-provisioning-vagrant (0.8.1)
chef-vault (2.4.0)
chef-zero (3.2.1, 1.5.6)
cheffish (0.9.2)
chefspec (4.2.0)
```

**Update chef-provisioning-aws and dependencies.  List versions:**
```
[18:33:20] (2) jreid@JoesMacBookPro:~
$ chef gem update chef-provisioning-aws
Updating installed gems
Updating chef-provisioning-aws
Fetching: specinfra-2.28.1.gem (100%)
Successfully installed specinfra-2.28.1
Fetching: rspec-support-3.2.2.gem (100%)
Successfully installed rspec-support-3.2.2
Fetching: rspec-expectations-3.2.1.gem (100%)
Successfully installed rspec-expectations-3.2.1
Fetching: rspec-core-3.2.3.gem (100%)
Successfully installed rspec-core-3.2.3
Fetching: rspec-its-1.2.0.gem (100%)
Successfully installed rspec-its-1.2.0
Fetching: rspec-mocks-3.2.1.gem (100%)
Successfully installed rspec-mocks-3.2.1
Fetching: rspec-3.2.0.gem (100%)
Successfully installed rspec-3.2.0
Fetching: serverspec-2.14.1.gem (100%)
Successfully installed serverspec-2.14.1
Fetching: rspec_junit_formatter-0.2.0.gem (100%)
Successfully installed rspec_junit_formatter-0.2.0
Fetching: chef-zero-4.2.1.gem (100%)
Successfully installed chef-zero-4.2.1
Fetching: chef-12.2.1.gem (100%)
Successfully installed chef-12.2.1
Fetching: cheffish-1.1.2.gem (100%)
Successfully installed cheffish-1.1.2
Fetching: chef-provisioning-1.0.1.gem (100%)
Successfully installed chef-provisioning-1.0.1
Fetching: chef-provisioning-aws-1.0.4.gem (100%)
Successfully installed chef-provisioning-aws-1.0.4
Gems updated: chef chef-provisioning chef-provisioning-aws chef-zero cheffish rspec rspec-core rspec-expectations rspec-its rspec-mocks rspec-support rspec_junit_formatter serverspec specinfra

[18:34:01] (3) jreid@JoesMacBookPro:~
$ chef gem list | grep chef
chef (12.2.1, 12.0.3)
chef-dk (0.4.0)
chef-provisioning (1.0.1, 0.18)
chef-provisioning-aws (1.0.4, 0.2.1)
chef-provisioning-azure (0.1)
chef-provisioning-fog (0.12)
chef-provisioning-vagrant (0.8.1)
chef-vault (2.4.0)
chef-zero (4.2.1, 3.2.1, 1.5.6)
cheffish (1.1.2, 0.9.2)
chefspec (4.2.0)
```

**Impact:**
A relatively simple recipe like the following 
```
require 'chef/provisioning/aws_driver'

machine 'chef_provisioning_test_node' do
  tag 'itsa_me_mario'
  recipe 'JO2O'
  with_machine_options :bootstrap_options => {
    :key_name => 'korrelate2012',
    :image_id => 'ami-2c348844',
  }
end
```

fails with `ERROR: undefined method `with_machine_options' for Chef::Resource::Machine` on chef-provisioning-aws (0.2.1), presumably do to the changes made since 0.2.1 was released:

```
[2015-04-11T18:31:20-04:00] FATAL: Stacktrace dumped to /Users/jreid/repo/chef-repo/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 4.297599 seconds
[2015-04-11T18:31:20-04:00] ERROR: undefined method `with_machine_options' for Chef::Resource::Machine
[2015-04-11T18:31:20-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

But an update to chef-provisioning-aws 1.0.4 means a chef-client -z simple.rb fails with the following:

```
[2015-04-11T18:35:18-04:00] ERROR: Unable to activate cheffish-1.1.2, because chef-zero-3.2.1 conflicts with chef-zero (~> 4.0)
[2015-04-11T18:35:18-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Regards,
Joe Reid

**Comment by JoeReid-Korrelate** [comment] 2015-04-12 00:04
Duplicate ticket with [#322](https://github.com/chef/chef-provisioning/issues/322), from chef-provisioning.  

Created it there before I realized this is probably more appropriate here.  Let me know, either way, and I will close the redundant ticket.

**Comment by stuartpreston** [comment] 2015-04-12 07:58
Closing this as a duplicate of [#322](https://github.com/chef/chef-provisioning/issues/322) where the issue resolution can be found.

**Closed by stuartpreston** 2015-04-12 07:58 UTC
